export const PUBLIC_GET_ALL_CATEGORIES_REQUEST = 'PUBLIC_GET_ALL_CATEGORIES_REQUEST'
export const PUBLIC_GET_ALL_CATEGORIES_SUCCESS = 'PUBLIC_GET_ALL_CATEGORIES_SUCCESS'
export const PUBLIC_GET_ALL_CATEGORIES_FAIL = 'PUBLIC_GET_ALL_CATEGORIES_FAIL'

export const ADMIN_CREATE_CATEGORY_REQUEST = 'ADMIN_CREATE_CATEGORY_REQUEST'
export const ADMIN_CREATE_CATEGORY_SUCCESS = 'ADMIN_CREATE_CATEGORY_SUCCESS'
export const ADMIN_CREATE_CATEGORY_FAIL = 'ADMIN_CREATE_CATEGORY_FAIL'
export const ADMIN_CREATE_CATEGORY_RESET = 'ADMIN_CREATE_CATEGORY_RESET'

export const ADMIN_DELETE_CATEGORY_REQUEST = 'ADMIN_DELETE_CATEGORY_REQUEST'
export const ADMIN_DELETE_CATEGORY_SUCCESS = 'ADMIN_DELETE_CATEGORY_SUCCESS'
export const ADMIN_DELETE_CATEGORY_FAIL = 'ADMIN_DELETE_CATEGORY_FAIL'
export const ADMIN_DELETE_CATEGORY_RESET = 'ADMIN_DELETE_CATEGORY_RESET'

export const ADMIN_UPDATE_CATEGORY_REQUEST = 'ADMIN_UPDATE_CATEGORY_REQUEST'
export const ADMIN_UPDATE_CATEGORY_SUCCESS = 'ADMIN_UPDATE_CATEGORY_SUCCESS'
export const ADMIN_UPDATE_CATEGORY_FAIL = 'ADMIN_UPDATE_CATEGORY_FAIL'
export const ADMIN_UPDATE_CATEGORY_RESET = 'ADMIN_UPDATE_CATEGORY_RESET'