export const PUBLIC_GET_MOVIE_LIST_REQUEST = 'PUBLIC_GET_MOVIE_LIST_REQUEST';
export const PUBLIC_GET_MOVIE_LIST_SUCCESS = 'PUBLIC_GET_MOVIE_LIST_SUCCESS';
export const PUBLIC_GET_MOVIE_LIST_FAIL = 'PUBLIC_GET_MOVIE_LIST_FAIL';

export const PUBLIC_GET_RANDOM_MOVIES_REQUEST = 'PUBLIC_GET_RANDOM_MOVIES_REQUEST';
export const PUBLIC_GET_RANDOM_MOVIES_SUCCESS = 'PUBLIC_GET_RANDOM_MOVIES_SUCCESS';
export const PUBLIC_GET_RANDOM_MOVIES_FAIL = 'PUBLIC_GET_RANDOM_MOVIES_FAIL';

export const PUBLIC_GET_MOVIE_BY_ID_REQUEST = 'PUBLIC_GET_MOVIE_BY_ID_REQUEST';
export const PUBLIC_GET_MOVIE_BY_ID_SUCCESS = 'PUBLIC_GET_MOVIE_BY_ID_SUCCESS';
export const PUBLIC_GET_MOVIE_BY_ID_FAIL = 'PUBLIC_GET_MOVIE_BY_ID_FAIL';
export const PUBLIC_GET_MOVIE_BY_ID_RESET = 'PUBLIC_GET_MOVIE_BY_ID_RESET';

export const PUBLIC_GET_TOP_RATED_MOVIES_REQUEST = 'PUBLIC_GET_TOP_RATED_MOVIES_REQUEST';
export const PUBLIC_GET_TOP_RATED_MOVIES_SUCCESS = 'PUBLIC_GET_TOP_RATED_MOVIES_SUCCESS';
export const PUBLIC_GET_TOP_RATED_MOVIES_FAIL = 'PUBLIC_GET_TOP_RATED_MOVIES_FAIL';

export const USER_CREATE_REVIEW_MOVIE_REQUEST = 'USER_CREATE_REVIEW_MOVIE_REQUEST';
export const USER_CREATE_REVIEW_MOVIE_SUCCESS = 'USER_CREATE_REVIEW_MOVIE_SUCCESS';
export const USER_CREATE_REVIEW_MOVIE_FAIL = 'USER_CREATE_REVIEW_MOVIE_FAIL';
export const USER_CREATE_REVIEW_MOVIE_RESET = 'USER_CREATE_REVIEW_MOVIE_RESET';

export const ADMIN_DELETE_MOVIE_REQUEST = 'ADMIN_DELETE_MOVIE_REQUEST';
export const ADMIN_DELETE_MOVIE_SUCCESS = 'ADMIN_DELETE_MOVIE_SUCCESS';
export const ADMIN_DELETE_MOVIE_FAIL = 'ADMIN_DELETE_MOVIE_FAIL';

export const ADMIN_DELETE_ALL_MOVIES_REQUEST = 'ADMIN_DELETE_ALL_MOVIES_REQUEST';
export const ADMIN_DELETE_ALL_MOVIES_SUCCESS = 'ADMIN_DELETE_ALL_MOVIES_SUCCESS';
export const ADMIN_DELETE_ALL_MOVIES_FAIL = 'ADMIN_DELETE_ALL_MOVIES_FAIL';

export const ADMIN_CREATE_MOVIE_REQUEST = "ADMIN_CREATE_MOVIE_REQUEST";
export const ADMIN_CREATE_MOVIE_SUCCESS = "ADMIN_CREATE_MOVIE_SUCCESS";
export const ADMIN_CREATE_MOVIE_FAIL = "ADMIN_CREATE_MOVIE_FAIL";
export const ADMIN_CREATE_MOVIE_RESET = "ADMIN_CREATE_MOVIE_RESET";

export const ADMIN_UPDATE_MOVIE_REQUEST = "ADMIN_UPDATE_MOVIE_REQUEST";
export const ADMIN_UPDATE_MOVIE_SUCCESS = "ADMIN_UPDATE_MOVIE_SUCCESS";
export const ADMIN_UPDATE_MOVIE_FAIL = "ADMIN_UPDATE_MOVIE_FAIL";
export const ADMIN_UPDATE_MOVIE_RESET = "ADMIN_UPDATE_MOVIE_RESET";

export const ADMIN_CREATE_CAST = "ADMIN_CREATE_CAST";
export const ADMIN_UPDATE_CAST = "ADMIN_UPDATE_CAST";
export const ADMIN_DELETE_CAST = "ADMIN_DELETE_CAST";
export const ADMIN_RESET_CAST = "ADMIN_RESET_CAST";
export const ADMIN_LOAD_CAST = "ADMIN_LOAD_CAST";

